apiVersion: v1
kind: Pod
metadata:
  name: leader-example-1
spec:
  containers:
    - image: leader-example:0.0.1
      imagePullPolicy: Never
      name: leader-example-image
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name